# Generated by Django 5.2.3 on 2025-07-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agily', '0002_issue_severity'),
        ('stories', '0012_storyattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstory',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agily.project'),
        ),
        migrations.AddField(
            model_name='story',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='agily.project'),
        ),
    ]
