# Generated by Django 5.2.3 on 2025-07-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agily', '0008_issueattachment_uploaded_by'),
        ('stories', '0014_historicalstory_project_story_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='agily.project'),
        ),
        migrations.AddField(
            model_name='historicalepic',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agily.project'),
        ),
    ]
