# Generated by Django 5.2.3 on 2025-07-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_epic_project_historicalepic_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epic',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalepic',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
