# Generated by Django 5.2.3 on 2025-07-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agily', '0002_issue_severity'),
        ('sprints', '0009_alter_sprint_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsprint',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agily.project'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='agily.project'),
        ),
    ]
