# Generated by Django 5.2.3 on 2025-07-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
    ]
