# Generated by Django 5.2.3 on 2025-07-02 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agily', '0002_issue_severity'),
        ('workspaces', '0005_auto_20240302_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace'),
            preserve_default=False,
        ),
    ]
