# Generated by Django 5.2.3 on 2025-07-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agily', '0004_issueattachment'),
        ('workspaces', '0005_auto_20240302_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'workspace')},
        ),
    ]
