# Generated by Django 5.2.3 on 2025-07-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agily', '0005_alter_project_name_alter_project_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='solution',
            field=models.TextField(blank=True, help_text='Solution provided by the developer.', null=True),
        ),
    ]
